name: ml_algo
description: Machine learning algorithms, Machine learning models performance evaluation functionality
version: 15.6.6
homepage: https://github.com/gyrdym/ml_algo

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  injector: ^1.0.9
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  ml_dataframe: ^0.4.0
  ml_linalg: ^12.17.10
  ml_preprocessing: ^5.2.2
  quiver: ^2.0.2
  xrange: ^1.0.0

dev_dependencies:
  benchmark_harness: '>=1.0.0 <2.0.0'
  build_runner: ^1.10.11
  mockito: ^3.0.0
  pedantic: ^1.9.2
  test: ^1.2.0
  test_coverage: ^0.5.0
