name: ml_algo
description: Machine learning algorithms, Machine learning models performance evaluation functionality
version: 16.17.14
homepage: https://github.com/gyrdym/ml_algo

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  injector: ^3.0.0
  json_annotation: ^4.0.0
  ml_dataframe: ^1.6.0
  ml_linalg: ^13.11.15
  ml_preprocessing: ^7.0.2
  quiver: ^3.0.0
  xrange: ^2.0.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.7.0
  lints: ^2.1.0
  mockito: ^5.0.10
  test: ^1.16.8
